### ISSUE TITLE
separate classes into files

### ISSUE THREAD

**Issue by mhassany** [mhassany/sit-ssw-555#3]
For better management, and merging; I think it makes it easier if we separate classes into multiple files.
For example: in case of reporting user stories implementation in excel sheet, we need to mention the source code line numbers. The line number changes because of future change (within sprint); or we can do it once after the sprint finishes.
What do you think?

**Comment by yalilu** [comment]
How about we record and check the number of line at the end of each sprint, and at the same time update the previous sprints‘ line numbers?
